version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /usr/src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -f Dockerfile.integration . -t 073020584345.dkr.ecr.us-east-1.amazonaws.com/lemon-mart:latest --build-arg CACHEBUST=$(date +%s)

# For Docker Hub deploy see https://circleci.com/docs/2.0/building-docker-images/
# For AWS ECS deploy see https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# For Heroku see https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-image-s
# For cache optimization read https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
